name: GBlog-$(SourceBranchName)-$(Date:yyyyMMdd)-$(Rev:.r)

trigger:
- "master"

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: "Build"
  displayName: "Build Hugo website"
  jobs:
  - job: "Hugo"
    displayName: "Download and run Hugo"
    steps:
    - bash:
        wget --tries 3 https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.tar.gz &&
        tar -xzvf hugo*.tar.gz hugo &&
        rm hugo*.tar.gz
    - bash: ./hugo --cleanDestinationDir --gc --ignoreCache --log --minify --noChmod

- stage: "Deploy"
  displayName: "Deploy to server"
  jobs:
  - deployment: "Upload"
    environment: "GBlog-prod"
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment
