name: GBlog-$(SourceBranchName)-$(Date:yyyyMMdd)-$(Rev:.r)

trigger:
- "master"

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: "Production"
  displayName: "Publish website to production"
  jobs:
  - job: "Build"
    displayName: "Download and run Hugo"
    steps:
    - bash:
        wget --tries 3 https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.tar.gz &&
        tar -xzvf hugo*.tar.gz hugo &&
        rm hugo*.tar.gz
    - bash: ls $(Pipeline.Workspace) && ./hugo --destination $(Pipeline.Workspace)
                   --cleanDestinationDir --gc --ignoreCache --log --minify --noChmod
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: "$(Pipeline.Workspace)"
        artifactName: "hugo-site"

  - deployment: "Deploy"
    displayName: "Deploy to server"
    dependsOn: "Build"
    environment: "GBlog-prod"
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: ls $(Pipeline.Workspac)
          