baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "G-Blog"
summaryLength = 60
paginate = 2
canonifyURLs = true
enableGitInfo = false
enableRobotsTXT = false
log = false
logFile = ""
relativeURLs = true
copyright = "Content is licensed under Creative Commons Attribution 4.0 International license"

[menu]
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    title = "Read our articles"
    url = "/"
    weight = -2

  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    title = "View helpful resources"
    url = "/resources/"
    weight = -1

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About us"
    url = "/about/"
    weight = 0

[mediaTypes."application/atom"]
  suffixes = ["atom.xml"]

[outputFormats.Atom]
  mediaType = "application/atom"

[outputs]
  home = ["HTML", "Atom"]
  section = ["HTML"]

[taxonomies]
  tag = "tags"

[related]
  threshold = 80
  includeNewer = true
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "keywords"
    weight = 70

  [[related.indices]]
    name = "date"
    weight = 10